SciML/SciMLOperators.jl

src/SciMLOperators.jl
src/basic.jl
src/interface.jl
src/sciml.jl
test/basic.jl
test/sciml.jl

https://github.com/SciML/SciMLOperators.jl/issues/17

5-argument mul!, 2-arg ldiv!

---

Project.toml
src/basic.jl
src/sciml.jl
test/Project.toml
test/runtests.jl
test/sciml.jl

- updated Project.toml, test/Project.toml
- cleaned FunctionOperator constructor
- fixed a faulty test
- cleaned clutter from test/runtes.jl

few small fixes

---

src/SciMLOperators.jl
src/basic.jl
src/interface.jl
src/sciml.jl
src/utils.jl
test/runtests.jl
test/sciml.jl

close https://github.com/SciML/SciMLOperators.jl/issues/23

Tensor Product Operator

---

src/basic.jl
src/matrix.jl

- more method ambiguities
- update behaviour for `DiagonalOperator`

small fixes

---

src/utils.jl

reshape of reshape is not a strided array

---

src/matrix.jl
test/matrix.jl

fix addvector

---

docs/src/tutorials/fftw.md

close https://github.com/SciML/SciMLOperators.jl/issues/115

update FFTW example in doc

---

src/basic.jl

fixed method ambig with +

---

docs/src/tutorials/fftw.md

fix https://github.com/SciML/SciMLOperators.jl/issues/123

fix fftw eg

---

src/basic.jl
src/scalar.jl
test/scalar.jl

Fix ambiguity errors when combining scalar operators with identity

---

src/basic.jl
src/scalar.jl
test/scalar.jl

There's probably some more to fill in, and definitely more to test, but resolves #134 for now. This PR is done on top of #133

Initial implementation of InvertedScalarOperator

---

src/SciMLOperators.jl
src/basic.jl
src/batch.jl
src/func.jl
src/interface.jl
src/left.jl
src/matrix.jl
src/scalar.jl
test/basic.jl
test/func.jl
test/matrix.jl
test/scalar.jl
test/total.jl

close https://github.com/SciML/SciMLOperators.jl/issues/106

remove abstractscimllinearoperator in favor or trait islinear(L)

---

src/SciMLOperators.jl
src/basic.jl
src/func.jl
src/interface.jl
src/tensor.jl
test/basic.jl
test/func.jl
test/matrix.jl
test/scalar.jl

close https://github.com/SciML/SciMLOperators.jl/issues/98

create and export trait `iscached(L)`

---

src/func.jl
src/interface.jl

fixed update_coefficients-bang, added getops, isconstant, for functionop
pls bump version after this. thanks

FunctionOperator fixes

---

src/func.jl
src/interface.jl
src/scalar.jl

fix https://github.com/SciML/DiffEqGPU.jl/pull/229

check first two dimensions for `issquare`

---

src/basic.jl
src/batch.jl
src/func.jl
src/interface.jl
src/matrix.jl
src/scalar.jl
src/tensor.jl
test/func.jl
test/matrix.jl
test/scalar.jl
test/total.jl

close https://github.com/SciML/SciMLOperators.jl/issues/171, close https://github.com/SciML/SciMLOperators.jl/issues/165

OOP update_coefficients(...)

---

src/matrix.jl

@xtalax merge and bump please? blocking https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917

fix typo in matrix.jl

---

src/func.jl
src/interface.jl
src/matrix.jl
test/basic.jl
test/func.jl
test/total.jl
test/zygote.jl

close https://github.com/SciML/SciMLOperators.jl/issues/84

Combine a forward operator with a backward operator for fast evaluaiton

---

src/basic.jl
src/interface.jl
src/scalar.jl
src/tensor.jl
test/zygote.jl

merge https://github.com/SciML/SciMLOperators.jl/pull/179 first

Test update_coeffs with Zygote

---

src/interface.jl
src/matrix.jl
src/scalar.jl
test/matrix.jl
test/scalar.jl

fix errors in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917
merge https://github.com/SciML/SciMLOperators.jl/pull/188 first

scalar op multiplcation fix when arguments are numbers

---

docs/src/index.md

Requires SciMLSensitivity change to be complete, then its prime time!

Remove warning on SciMLOperators incompleteness

---

src/SciMLOperators.jl
src/interface.jl

fix https://github.com/SciML/SciMLOperators.jl/issues/192#event-9389944941

rm warning

---

src/interface.jl

fix https://github.com/SciML/LinearSolve.jl/actions/runs/5417914034/jobs/9849418672?pr=337#step:6:13263

clean up convert-based fallbacks

---

.JuliaFormatter.toml
.github/workflows/CI.yml
.github/workflows/FormatCheck.yml
docs/Project.toml
docs/make.jl
docs/src/index.md
docs/src/interface.md
docs/src/sciml.md
docs/src/tutorials/fftw.md
src/func.jl
src/matrix.jl
src/scalar.jl

Also adds formatter workflow in anticipation of formatter being fixed.
Formatting has thus not yet been applied.

Documenter 1.0 upgrade.

---

README.md
docs/src/tutorials/operator_algebras.md
src/func.jl
src/tensor.jl

Fixes https://github.com/SciML/SciMLOperators.jl/issues/252

Fix operator algebras tutorial

---

src/tensor.jl

Fix 2 spelling errors: permut -> permute in tensor.jl comments

Fix spelling errors
