src/SciMLOperators.jl
src/sciml.jl
test/sciml.jl

- clarify TensorProductOperator constructor.
- fixed overloads now,  `kron(...) isa AbstractMatrix`, `\otimes(...) isa TensorProductOperator`
- remove redundant +,-,*(SciMLOperator, UniformScaling) methods
- ~exporting `\otimes` as it does not conflict with anything in Base or LinearAlgebra~

small fixes

---

src/basic.jl
src/sciml.jl
src/utils.jl
test/sciml.jl

fixes https://github.com/SciML/SciMLOperators.jl/issues/58
```julia
using SciMLOperators, LinearAlgebra
using BenchmarkTools
A = TensorProductOperator(rand(12,12), rand(12,12), rand(12,12))
u = rand(12^3, 100)
v = rand(12^3, 100)
A = cache_operator(A, u)
mul!(v, A, u) # dunny
@btime mul!($v, $A, $u); # 4.510 ms (17 allocations: 31.36 KiB)
```
```julia
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
OS: macOS (x86_64-apple-darwin21.4.0)
CPU: 4 × Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
Threads: 4 on 4 virtual cores
Environment:
JULIA_NUM_PRECOMPILE_TASKS = 4
JULIA_DEPOT_PATH = /Users/vp/.julia
JULIA_NUM_THREADS = 4
```
this is on par with linearmaps in terms of …

Faster TensorProductOperator

---

Project.toml
src/batch.jl
src/interface.jl
src/left.jl
src/multidim.jl
src/tensor.jl
src/utils.jl

fix https://github.com/SciML/SciMLOperators.jl/issues/91
just to make sure, im comparing performance on `benchmark/tensor.jl` with `_reshape, _vec`, and without.
with `_reshape, _vec` - https://github.com/SciML/SciMLOperators.jl/pull/92/commits/f2b7fe9045481d792826b2bad7a362ce35d6fde3
```julia
[vp@MBP benchmarks]:jl
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.8.0-rc3 (2022-07-13)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> versioninfo()
Julia Version 1.8.0-rc3
Commit 33f19bcbd25 (2022-07-13 19:10 UTC)
Platform Info:
OS: macOS (x86_64-apple-darwin21.4.0)
CPU: 4 × Intel(R) …
```

using `Base.ReshapedArray` is unnecessary

---

README.md
docs/make.jl

I updated the docs as per the new Sciml doc specs.
NOTE:
I noticed in `make.jl` that the canonical link was originally pointing to `SciMLBase`, 
https://scimlbase.sciml.ai/stable/
That seems like a possible error to me, so I replaced it with the direct SciMLOperators link, which works. If I made an error in judgement, please let me know and I can revert that particular change.

updated README and make.jl to sciml doc standard.

---

src/basic.jl
test/basic.jl

- The operators shouldn't be reversed in the composed operator factorization
~- The composed operator caching relies on matmuls, but when composing certain factorizations the inner ops may in fact not support matmuls. I used the size instead, which seems more robust?~

Fix composed operator factorization

---

src/basic.jl
src/tensor.jl
test/basic.jl
test/matrix.jl

Just adds a couple missing lazy factorizations, in the same spirit as the existing factorization for a composed operator. When writing tests I found a few bugs with the tensor product operator itself; I fixed a couple typos but made an issue (#127) for the remaining bugs.

Add missing lazy factorizations for scaled operators and tensor operators

---

src/matrix.jl
test/matrix.jl

This prepares the ground for https://github.com/JuliaLang/julia/pull/46874. The const definition and the method signatures are harmless for older Julia versions. I also rearranged the `convert` functions and used multiple dispatch. I don't know why, but the changes fix a broken test on Julia v1.9, but not older.

Prepare for `AdjointFactorization`, multiple dispatch

---

Project.toml
src/basic.jl
src/matrix.jl
src/scalar.jl
src/tensor.jl
test/basic.jl
test/scalar.jl
test/zygote.jl

This both improves the performance of compile time and run times downstream by a lot. Such information should not be put into type space!
Bumps as a breaking change
Fixes https://github.com/SciML/SciMLOperators.jl/issues/154

Remove unnecessary type information in identity and null operators

---

src/func.jl
src/interface.jl
test/func.jl
test/matrix.jl
test/scalar.jl

close https://github.com/SciML/SciMLOperators.jl/issues/151, https://github.com/SciML/SciMLOperators.jl/issues/48

Support `L(v, u, p, t, a, b)` corresponding to 5 arg `mul!`

---

src/func.jl

This is causing warnings in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917
merge and minor bump please? @xtalax

fix typo that's causing warnings

---

src/interface.jl
src/scalar.jl
test/scalar.jl

they can also infer type now
fix errors in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917 (linear-nonlinear method test)

fixed scalaroperator convert methods. 

---

Project.toml
src/SciMLOperators.jl
src/interface.jl

This fixes the warning
```julia
julia> using SciMLOperators
[ Info: Precompiling SciMLOperators [c0aeaf25-5076-4817-a8d5-81caf7dfa961]
┌ Warning: Replacing docs for `SciMLOperators.AbstractSciMLOperator :: Union{}` in module `SciMLOperators`
└ @ Base.Docs docs/Docs.jl:243
```
Without this patch, the docstring added in
https://github.com/SciML/SciMLOperators.jl/blob/1f8297b0d4c3f62c0f05007f38cd07b3fe12fdd7/src/SciMLOperators.jl#L21-L24
was overwritten (and not available anymore) for me.

fix warning

---

docs/src/interface.md
src/batch.jl
src/func.jl
src/interface.jl
src/matrix.jl
src/scalar.jl
src/utils.jl
test/func.jl
test/scalar.jl
test/total.jl

Resolves #125. For example usage, see the added test for a scalar operator. ~I left function operator mostly alone because I don't understand some aspects of it, and from some of the other issues it seems it still might be in flux. More comprehensive tests can be added in a follow up PR, but note that this change is totally backwards compatible.~ (Addressed)
For developers of this library, this is what you should know about the new design:
- Operator constructors called by the user should accept `update_func` and `accepted_kwargs` arguments, and preprocess them using the `preprocess_update_func` utility before making the struct, as done here.
- For internal calls to constructors where the `update_func` has already been processed, `accepted_kwargs` should be set to `NoKwargFilter()`, which …

Propagate kwargs through update_coefficients!

---

src/func.jl
test/func.jl

fix https://github.com/SciML/DiffEqBase.jl/actions/runs/5337907412/jobs/9674567530?pr=913#step:6:875

add method `cache_internals(::FunctionOp, ::AbstractArray)`

---

src/interface.jl

Add back fallback methods in https://github.com/SciML/SciMLOperators.jl/pull/208
fix https://github.com/SciML/SciMLOperators.jl/actions/runs/5437055376/jobs/9887334855#step:6:1143
with this branch,
```julia
julia> using SciMLOperators
julia> A = MatrixOperator(rand(4,4));
julia> B = A + A \ A * A
(MatrixOperator(4 × 4) + (1 / MatrixOperator(4 × 4) * MatrixOperator(4 × 4) * MatrixOperator(4 × 4)))
julia> sum(A)
┌ Warning: using convert-based fallback in sum.
└ @ SciMLOperators ~/.julia/dev/SciMLOperators/src/interface.jl:385
7.445259168454413
julia> sum(A; dims = 1)
┌ Warning: using convert-based fallback in sum.
└ @ SciMLOperators ~/.julia/dev/SciMLOperators/src/interface.jl:385
1×4 Matrix{Float64}:
1.31282  2.63051  1.71377  1.78816
```
ODE/InterfaceII tests passing locally with this …

sum, prod fallbacks

---

docs/src/tutorials/fftw.md
src/func.jl
test/func.jl
test/total.jl

@ChrisRackauckas 
with this branch,
```julia
julia> f(u, p, t) = 2u; f(v, u, p, t) = mul!(v, 2, u);                                                                                                               [30/1927]
julia> F = FunctionOperator(f, ones(4, 4));
julia> F * ones(4, 4)
4×4 Matrix{Float64}:
2.0  2.0  2.0  2.0
2.0  2.0  2.0  2.0
2.0  2.0  2.0  2.0
2.0  2.0  2.0  2.0                        
julia> F * vec(ones(4, 4))
16-element Vector{Float64}:
2.0
2.0
2.0
2.0
2.0
...
julia> mul!(zeros(16), F, ones(16))
16-element Vector{Float64}:
2.0
2.0
2.0
2.0
2.0
...
```

allow functionoperator (batch = false) to accept/return vec'd arrays

---

Project.toml
src/SciMLOperators.jl
src/basic.jl
src/batch.jl
src/func.jl
src/interface.jl
src/matrix.jl
src/scalar.jl
src/tensor.jl

fix https://github.com/SciML/SciMLOperators.jl/issues/196
@ChrisRackauckas what is the expected heuristic here? Currently this only checks if we can convert to `AbstractMatrix`. Not if that's efficient or preferable.
Does `isconcrete(L) == true` implies we can `getindex`/ `setindex!`? Do we want separate traits `can_setindex, can_getindex`?
We can simplify the workflow to just two functions
- `isconvertible` indicating if `L` can be converted (cheaply) to an `AbstractMatrix`. This is true for lazy combinations of ScalarOp, MatrixOp, but not for TensorProdOp, InvertedOp. For FunctionOp, the behaviour can be set with kwarg `isconvertible`.
- `concretize(L)` returns a concrete type for `L`. It is a no-op when `L` is already concrete.
workflow in downstream packages:
```julia
if …
```

concretize methods

---

src/interface.jl

Gets rid of a lot of noise in OrdinaryDiffEq mass matrix tests

Only warn about convert-based fallbacks when operator not convertible.

---

src/basic.jl
src/func.jl
src/utils.jl

Branched off https://github.com/SciML/SciMLOperators.jl/pull/224
Some of the traits needed to be hoisted from the traits NamedTuple to the type. 
xref: https://github.com/JuliaDiff/SparseDiffTools.jl/pull/272#discussion_r1382391742

Make Function Operator Type Stable

---

docs/Project.toml
docs/src/tutorials/fftw.md

Fix: #228 
Add any other context about the problem here.

Fix forward and inverse application in FFTW tutorial

---

.github/workflows/CI.yml
.github/workflows/Downstream.yml
Project.toml
src/SciMLOperators.jl
src/func.jl

After that entire discussion on slack regarding SimpleNonlinearSolve precompile times. It seems we are installing packages that are not needed in 1.10+.
This + some SciMLBase changes:
```julia
julia> @time using SciMLOperators, SciMLBase
0.137750 seconds (160.93 k allocations: 16.369 MiB)
julia> @time using SciMLOperators, SciMLBase
0.090675 seconds (113.75 k allocations: 13.515 MiB)
```

Remove Packages that are no longer needed in 1.10

---

src/matrix.jl

Correct the typo in the documentation of SciMLOperators.MatrixOperator.

Correct typo

---

Project.toml
ext/SciMLOperatorsStaticArraysCoreExt.jl
src/SciMLOperators.jl
src/basic.jl
src/batch.jl
src/left.jl
src/matrix.jl
src/scalar.jl
src/tensor.jl

[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
I saw that SciMLBase depends both on Accessors and SetField. this PR migrates the uses of SetField to Accessors, and moves StaticArraysCore to an extension (in this way, StaticArraysCore is not loaded anymore)

migrate to Accessors, move StaticArraysCore to ext

---

src/basic.jl

This PR fixes #247.
A dedicated `update_coefficients!` method for in-place update of `ScaledOperator` was missing.
I've just added that method.

Add missing inplace update_coefficients for `ScaledOperator`

---

src/basic.jl
src/func.jl
src/utils.jl
test/func.jl

The current implementation of `FunctionOperator` requires a `Dict{Symbol,Any}` to handle the keyword arguments. This leads to type instabilities and performance decreases, as in the following simple code:
```julia
using LinearAlgebra
using BenchmarkTools
using SciMLOperators
T = ComplexF64
N = 10
u = rand(T, N)
du = similar(u)
p = (A=rand(T, N, N),)
op = FunctionOperator((du, u, p, t) -> mul!(du, p.A, u), u, p = p, T=T, isinplace=Val(true), outofplace=Val(true), has_mul5=Val(true), isconstant=true)
op(du, u, p, 0.1)
@benchmark $op($du, $u, $p, 0.1)
```
```julia-repl
BenchmarkTools.Trial: 10000 samples with 53 evaluations.
Range (min … max):  864.434 ns … 104.262 μs  ┊ GC (min … max): 0.00% … 98.52%
Time  (median):     947.340 ns               ┊ GC (median):    0.00%
Time  (mean ± σ): …
```

Remove `Dict{Symbol, Any}` for type stability in `FunctionOperator`

---

src/interface.jl

This fixes a DiffEqBase type piracy that was relied on downstream.

All necessary fallbacks to the interface definition

---

src/basic.jl

Here I add more methods on the multiplication of constant scalars like `Number` or `UniformScalar`.
This will simplify the structure of the nested operators, when applicable.

Add special methods for multiplication of constant scalars

---

src/func.jl
test/func.jl

mul! for out-of-place FunctionOperators was added in #275, but with a typo: a missing argument name. This PR adds the argument name and a test.
Now that `mul!` exists for oop FunctionOperators, should `has_mul!`  at https://github.com/SciML/SciMLOperators.jl/blob/41a4dc6b4424e164fb595603f849022c05823c09/src/func.jl#L622 be changed to always return true?

mul! for out-of-place FunctionOperator
